# Generated by Django 3.1.3 on 2023-08-09 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hater',
            field=models.ManyToManyField(related_name='hater_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='hater',
            field=models.ManyToManyField(related_name='hater_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
